# Covid Analysis

This is the first part of the covid analysis project. I will be doing some cleaning and formatting for further exploration in SQL.

In [22]:
import pandas as pd
import numpy as np

In [16]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

## Data Import and Exploration

In [2]:
df = pd.read_csv('./owid_covid_data.csv')

In [3]:
df.head()

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,2020-01-05,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2020-01-06,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2020-01-07,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2020-01-08,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2020-01-09,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 367931 entries, 0 to 378555
Data columns (total 67 columns):
 #   Column                                      Non-Null Count   Dtype
---  ------                                      --------------   -----
 0   iso_code                                    367931 non-null  object
 1   continent                                   350447 non-null  object
 2   location                                    367931 non-null  object
 3   date                                        367931 non-null  object
 4   total_cases                                 329545 non-null  float64
 5   new_cases                                   357646 non-null  float64
 6   new_cases_smoothed                          356416 non-null  float64
 7   total_deaths                                307783 non-null  float64
 8   new_deaths                                  357654 non-null  float64
 9   new_deaths_smoothed                         356424 non-null  float64
 10  total_cases_per_million                     329545 non-null  float64
 11  new_cases_per_million                       357646 non-null  float64
 12  new_cases_smoothed_per_million              356416 non-null  float64
 13  total_deaths_per_million                    307783 non-null  float64
 14  new_deaths_per_million                      357654 non-null  float64
 15  new_deaths_smoothed_per_million             356424 non-null  float64
 16  reproduction_rate                           184817 non-null  float64
 17  icu_patients                                38131 non-null   float64
 18  icu_patients_per_million                    38131 non-null   float64
 19  hosp_patients                               39576 non-null   float64
 20  hosp_patients_per_million                   39576 non-null   float64
 21  weekly_icu_admissions                       10449 non-null   float64
 22  weekly_icu_admissions_per_million           10449 non-null   float64
 23  weekly_hosp_admissions                      23763 non-null   float64
 24  weekly_hosp_admissions_per_million          23763 non-null   float64
 25  total_tests                                 79387 non-null   float64
 26  new_tests                                   75403 non-null   float64
 27  total_tests_per_thousand                    79387 non-null   float64
 28  new_tests_per_thousand                      75403 non-null   float64
 29  new_tests_smoothed                          103965 non-null  float64
 30  new_tests_smoothed_per_thousand             103965 non-null  float64
 31  positive_rate                               95927 non-null   float64
 32  tests_per_case                              94348 non-null   float64
 33  tests_units                                 106788 non-null  object
 34  total_vaccinations                          81629 non-null   float64
 35  people_vaccinated                           77733 non-null   float64
 36  people_fully_vaccinated                     74504 non-null   float64
 37  total_boosters                              49785 non-null   float64
 38  new_vaccinations                            67550 non-null   float64
 39  new_vaccinations_smoothed                   187864 non-null  float64
 40  total_vaccinations_per_hundred              81629 non-null   float64
 41  people_vaccinated_per_hundred               77733 non-null   float64
 42  people_fully_vaccinated_per_hundred         74504 non-null   float64
 43  total_boosters_per_hundred                  49785 non-null   float64
 44  new_vaccinations_smoothed_per_million       187864 non-null  float64
 45  new_people_vaccinated_smoothed              185593 non-null  float64
 46  new_people_vaccinated_smoothed_per_hundred  185593 non-null  float64
 47  stringency_index                            197292 non-null  float64
 48  population_density                          312576 non-null  float64
 49  median_age                                  290613 non-null  float64
 50  aged_65_older                               280522 non-null  float64
 51  aged_70_older                               287699 non-null  float64
 52  gdp_per_capita                              284893 non-null  float64
 53  extreme_poverty                             183591 non-null  float64
 54  cardiovasc_death_rate                       285472 non-null  float64
 55  diabetes_prevalence                         300125 non-null  float64
 56  female_smokers                              214188 non-null  float64
 57  male_smokers                                211274 non-null  float64
 58  handwashing_facilities                      139877 non-null  float64
 59  hospital_beds_per_thousand                  252070 non-null  float64
 60  life_expectancy                             338694 non-null  float64
 61  human_development_index                     276813 non-null  float64
 62  population                                  367931 non-null  float64
 63  excess_mortality_cumulative_absolute        13113 non-null   float64
 64  excess_mortality_cumulative                 13113 non-null   float64
 65  excess_mortality                            13113 non-null   float64
 66  excess_mortality_cumulative_per_million     13113 non-null   float64
dtypes: float64(62), object(5)
memory usage: 190.9+ MB

## Data Cleaning

### 1. Date

I will format the datetime column, and I only want to keep the data from 2020-01-01 to 2023-12-31, which is 4 years of data in total.

In [5]:
df['date'] = pd.to_datetime(df['date'])

In [10]:
df['date'] = df['date'].dt.strftime('%Y-%m-%d')

In [12]:
print(df['date'].min())
print(df['date'].max())

2020-01-01
2024-02-26

In [13]:
df = df[df['date'] <= '2023-12-31']

In [14]:
print(df['date'].min())
print(df['date'].max())

2020-01-01
2023-12-31

### 2. Integer

Convert columns into integer format.

In [28]:
df.fillna(0, inplace=True)

In [33]:
to_integer = ['total_cases', 'new_cases', 'total_deaths', 'new_deaths', 'icu_patients', 'hosp_patients', 
              'weekly_icu_admissions', 'weekly_hosp_admissions', 'total_tests', 'new_tests', 
              'total_vaccinations', 'people_vaccinated', 'people_fully_vaccinated', 'total_boosters', 
              'new_vaccinations','population']

df[to_integer] = df[to_integer].astype(int)

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 367931 entries, 0 to 378555
Data columns (total 67 columns):
 #   Column                                      Non-Null Count   Dtype
---  ------                                      --------------   -----
 0   iso_code                                    367931 non-null  object
 1   continent                                   367931 non-null  object
 2   location                                    367931 non-null  object
 3   date                                        367931 non-null  object
 4   total_cases                                 367931 non-null  int64
 5   new_cases                                   367931 non-null  int64
 6   new_cases_smoothed                          367931 non-null  float64
 7   total_deaths                                367931 non-null  int64
 8   new_deaths                                  367931 non-null  int64
 9   new_deaths_smoothed                         367931 non-null  float64
 10  total_cases_per_million                     367931 non-null  float64
 11  new_cases_per_million                       367931 non-null  float64
 12  new_cases_smoothed_per_million              367931 non-null  float64
 13  total_deaths_per_million                    367931 non-null  float64
 14  new_deaths_per_million                      367931 non-null  float64
 15  new_deaths_smoothed_per_million             367931 non-null  float64
 16  reproduction_rate                           367931 non-null  float64
 17  icu_patients                                367931 non-null  int64
 18  icu_patients_per_million                    367931 non-null  float64
 19  hosp_patients                               367931 non-null  int64
 20  hosp_patients_per_million                   367931 non-null  float64
 21  weekly_icu_admissions                       367931 non-null  int64
 22  weekly_icu_admissions_per_million           367931 non-null  float64
 23  weekly_hosp_admissions                      367931 non-null  int64
 24  weekly_hosp_admissions_per_million          367931 non-null  float64
 25  total_tests                                 367931 non-null  int64
 26  new_tests                                   367931 non-null  int64
 27  total_tests_per_thousand                    367931 non-null  float64
 28  new_tests_per_thousand                      367931 non-null  float64
 29  new_tests_smoothed                          367931 non-null  float64
 30  new_tests_smoothed_per_thousand             367931 non-null  float64
 31  positive_rate                               367931 non-null  float64
 32  tests_per_case                              367931 non-null  float64
 33  tests_units                                 367931 non-null  object
 34  total_vaccinations                          367931 non-null  int64
 35  people_vaccinated                           367931 non-null  int64
 36  people_fully_vaccinated                     367931 non-null  int64
 37  total_boosters                              367931 non-null  int64
 38  new_vaccinations                            367931 non-null  int64
 39  new_vaccinations_smoothed                   367931 non-null  float64
 40  total_vaccinations_per_hundred              367931 non-null  float64
 41  people_vaccinated_per_hundred               367931 non-null  float64
 42  people_fully_vaccinated_per_hundred         367931 non-null  float64
 43  total_boosters_per_hundred                  367931 non-null  float64
 44  new_vaccinations_smoothed_per_million       367931 non-null  float64
 45  new_people_vaccinated_smoothed              367931 non-null  float64
 46  new_people_vaccinated_smoothed_per_hundred  367931 non-null  float64
 47  stringency_index                            367931 non-null  float64
 48  population_density                          367931 non-null  float64
 49  median_age                                  367931 non-null  float64
 50  aged_65_older                               367931 non-null  float64
 51  aged_70_older                               367931 non-null  float64
 52  gdp_per_capita                              367931 non-null  float64
 53  extreme_poverty                             367931 non-null  float64
 54  cardiovasc_death_rate                       367931 non-null  float64
 55  diabetes_prevalence                         367931 non-null  float64
 56  female_smokers                              367931 non-null  float64
 57  male_smokers                                367931 non-null  float64
 58  handwashing_facilities                      367931 non-null  float64
 59  hospital_beds_per_thousand                  367931 non-null  float64
 60  life_expectancy                             367931 non-null  float64
 61  human_development_index                     367931 non-null  float64
 62  population                                  367931 non-null  int64
 63  excess_mortality_cumulative_absolute        367931 non-null  float64
 64  excess_mortality_cumulative                 367931 non-null  float64
 65  excess_mortality                            367931 non-null  float64
 66  excess_mortality_cumulative_per_million     367931 non-null  float64
dtypes: float64(46), int64(16), object(5)
memory usage: 190.9+ MB

### Exploring

In [35]:
location_data = df.groupby('location').agg({
    'total_cases': 'sum',
    'total_deaths': 'sum',
    'total_tests': 'sum',
    'total_vaccinations': 'sum',
    'population': 'max'
}).reset_index()

location_data

,location,total_cases,total_deaths,total_tests,total_vaccinations,population
0,Afghanistan,195299872,7748447,4623226,1659147079,41128772
1,Africa,11765133447,250731764,0,491518103707,1426736614
2,Albania,282945078,3537918,402943865,395364296,2842318
3,Algeria,262400177,6916091,230553,298397256,44903228
4,American Samoa,5080174,20831,0,0,44295
5,Andorra,38617686,173325,13793707,5846260,79843
6,Angola,91142257,1799159,42850383,1398489266,35588996
7,Anguilla,2724972,8167,83038,1290079,15877
8,Antigua and Barbuda,6981638,123150,93919,7482788,93772
9,Argentina,8622509013,133006803,12012396105,90608316357,45510324
10,Armenia,417673371,8277406,993691238,58724412,2780472
11,Aruba,34895866,232503,1158,98549903,106459
12,Asia,186765354989,1435244442,0,7109003697162,4721383370
13,Australia,6759002537,12607803,22548370394,19215709854,26177410
14,Austria,3988620113,20287072,50028297751,1897828020,8939617
15,Azerbaijan,737293789,9267601,1123356006,3516610796,10358078
16,Bahamas,32660583,744153,25270142,14574520,409989
17,Bahrain,560987849,1516259,2283273595,1422980218,1472237
18,Bangladesh,1909652853,28759241,4301702570,93507647088,171186368
19,Barbados,71158151,406999,22772103,128989451,281646
20,Belarus,885129667,6440769,1569029848,618646885,9534956
21,Belgium,3696701147,35839353,12048773120,23293885544,11655923
22,Belize,54893830,641496,16586189,43105462,405285
23,Benin,25091319,166672,604310,75757734,13352864
24,Bermuda,13486510,127586,167106,5297377,64207
25,Bhutan,40774018,14406,323826981,123582319,782457
26,Bolivia,955939561,22934012,1346922093,5077109541,12224114
27,Bonaire Sint Eustatius and Saba,8475188,33081,0,43236,27052
28,Bosnia and Herzegovina,365990814,15139537,303979509,13550064,3233530
29,Botswana,270346618,2500778,162464685,97855111,2630300
30,Brazil,32135553347,693174330,12343376260,201902296883,215313504
31,British Virgin Islands,5603745,51962,96630,1606945,31332
32,Brunei,170507783,105514,278698,91439727,449002
33,Bulgaria,1063004324,34121378,1411537407,3361818134,6781955
34,Burkina Faso,21055415,362678,5325002,78794911,22673764
35,Burundi,39215499,14260,55788184,1239744,12889583
36,Cambodia,120275968,2643568,183934404,9643091200,16767851
37,Cameroon,120823372,1949318,20962624,124168712,27914542
38,Canada,3620459593,45277484,24135654211,77241758059,38454328
39,Cape Verde,56336620,403722,0,28244587,593162
40,Cayman Islands,21231350,24677,22004,12327845,68722
41,Central African Republic,15566563,126127,1489957,73101000,5579148
42,Chad,7461557,219994,4571170,140069916,17723312
43,Chile,3900589531,56238040,12661571719,30944353974,19603736
44,China,38231162641,52778574,9464000000,1712764057700,1425887360
45,Colombia,6074816991,142377904,11996864475,13622574899,51874028
46,Comoros,7789364,167593,106516,12682906,836783
47,Congo,23588501,366335,783046,16093094,5970430
48,Cook Islands,4197144,947,0,698904,17032
49,Costa Rica,940935349,8368565,960596311,610119336,5180836
50,Cote d'Ivoire,83954985,763303,369362403,612666548,28160548
51,Croatia,1022441098,15424693,958599002,2823937824,4030361
52,Cuba,952732290,7441312,717015431,24277223246,11212198
53,Curacao,36638978,249904,113826,92495552,191173
54,Cyprus,447720848,1027229,5872663133,188496747,896007
55,Czechia,3820784958,41017952,19252136204,15143546047,10493990
56,Democratic Republic of Congo,85802578,1469375,24196104,185300704,99010216
57,Denmark,2443813898,6478753,23525029451,1549786550,5882259
58,Djibouti,16425629,199262,6718280,13783019,1120851
59,Dominica,11260483,54163,4466990,4721992,72758
60,Dominican Republic,593976630,4889761,604311544,8006946662,11228821
61,Ecuador,896151652,36986408,1031547208,12151626804,18001002
62,Egypt,485680346,24525761,42097790,6205654190,110990096
63,El Salvador,172631112,4136785,533038829,1025170782,6336393
64,England,0,0,0,82412239538,56550000
65,Equatorial Guinea,16551606,193614,19835536,26882570,1674916
66,Eritrea,9222889,84334,23693,0,3684041
67,Estonia,462856080,2391806,1171062600,1782582827,1326064
68,Eswatini,64940901,1357719,13294674,34000504,1201680
69,Ethiopia,468116062,7257691,1250759770,2111954044,123379928
70,Europe,181974390432,1905421234,0,1159293683813,744807803
71,European Union,131050112856,1153391958,0,792659038481,450146793
72,Faeroe Islands,24870238,20874,22082276,8612023,53117
73,Falkland Islands,1165113,0,0,14163,3801
74,Fiji,57078503,726085,73025371,125446455,929769
75,Finland,990490260,6076082,4009062762,1781065692,5540745
76,France,26814410938,161046500,83214454871,102952720068,67813000
77,French Guiana,79248651,370447,0,0,304568
78,French Polynesia,65743735,587340,0,17281651,306292
79,Gabon,45936543,292067,96759694,14821139,2388997
80,Gambia,12157577,364134,8723641,14700467,2705995
81,Georgia,1444067060,14643562,2503040821,478298998,3744385
82,Germany,25042631495,152421374,6628848380,109617918285,83369840
83,Ghana,168684822,1406404,478626487,556044211,33475870
84,Gibraltar,15941525,111770,4197278,19047549,32677
85,Greece,3462422534,29036180,10303630956,17901897179,10384972
86,Greenland,8671853,14364,0,6166074,56494
87,Grenada,13918018,188377,3916246,6440866,125459
88,Guadeloupe,143886467,882167,0,0,395762
89,Guam,38182946,354262,104560779,0,171783
90,Guatemala,944750518,18305711,979067368,3221764974,17843914
91,Guernsey,22592532,51825,0,11186003,63329
92,Guinea,38432942,427713,9563341,434860738,13859349
93,Guinea-Bissau,8609604,166343,3094602,24490872,2105580
94,Guyana,58876756,1127375,868509,72472500,808727
95,Haiti,32243825,824886,5752410,16418951,11585003
96,High income,300484746456,2654873939,0,2309448197947,1250514600
97,Honduras,441166057,10991692,0,708069763,10432858
98,Hong Kong,0,0,483796487,13010914685,7488863
99,Hungary,1789960764,44515938,2593088077,892188028,9967304
100,Iceland,142185744,122574,410087509,51942584,372903
101,India,42307188589,520876982,296477930381,1640602444757,1417173120
102,Indonesia,5692139870,147870946,10136430783,77948522932,275501344
103,Iran,6842088651,143476321,8890509275,21579318120,88550568
104,Iraq,2331589335,26577509,4345669611,1082797012,44496124
105,Ireland,1305729947,8277885,4395350613,9426906927,5023108
106,Isle of Man,27410514,104311,0,29238064,84534
107,Israel,3639627951,11283834,15942816188,12735673809,9449000
108,Italy,17718170841,184050835,63349522489,112298543444,59037472
109,Jamaica,128257948,2885345,232701883,392377889,2827382
110,Japan,17236783562,44144937,13429500083,183641193499,123951696
111,Jersey,45484071,138824,0,24636147,110796
112,Jordan,1503314407,13594570,2355728265,1323570689,11285875
113,Kazakhstan,1305959407,17716101,1970609383,3623784535,19397998
114,Kenya,322148549,5594461,255448354,2066060051,54027484
115,Kiribati,2881721,11987,0,2941577,131237
116,Kosovo,233114509,3253522,235263616,729933970,1782115
117,Kuwait,608535085,2677424,1801264237,1044825806,4268886
118,Kyrgyzstan,73660658,851965,0,2093051767,6630621
119,Laos,156507850,492722,122421960,568620611,7529477
120,Latvia,698355067,5970688,2359764225,923635334,1850654
121,Lebanon,1058916216,10378808,112679216,1239009378,5489744
122,Lesotho,30417181,668936,10125965,21060351,2305826
123,Liberia,7418375,299691,139824,54160620,5302690
124,Libya,457193842,6052561,0,275909321,6812344
125,Liechtenstein,15309742,84040,21603454,18520110,39355
126,Lithuania,998809481,8471709,3014872686,3383364995,2750058
127,Low income,2076326196,45612963,0,170256492056,737604900
128,Lower middle income,85574969927,1267736167,0,3607966403637,3432097300
129,Luxembourg,266555454,890840,1958343804,684641413,647601
130,Macao,0,0,0,384291451,695180
131,Madagascar,64313957,1324293,40422406,104050549,29611718
132,Malawi,80726333,2520383,44116088,418372551,20405318
133,Malaysia,3876860017,30628504,17006807176,59210535782,33938216
134,Maldives,154420564,289234,571025854,214353973,523798
135,Mali,28984296,744969,17019330,154473262,22593598
136,Malta,91291787,749212,732368441,740651904,533293
137,Marshall Islands,7847703,8473,6872,0,41593
138,Martinique,156244919,859948,0,0,367512
139,Mauritania,55979192,1005021,44669727,139339674,4736146
140,Mauritius,199009368,779985,2924923,135370418,1299478
141,Mayotte,36631160,201962,0,0,326113
142,Mexico,6260363447,348829062,5729184899,33330559315,127504120
143,Micronesia (country),11854622,29689,0,0,114178
144,Moldova,525501918,11270911,0,373730654,3272993
145,Monaco,11823486,56655,0,867304,36491
146,Mongolia,785609822,1824097,1109328885,1178950405,3398373
147,Montenegro,210258091,2461047,0,225015167,627082
148,Montserrat,825569,5510,0,171218,4413
149,Morocco,1177099545,16262915,3900638082,8160864818,37457976
150,Mozambique,205365693,2069161,267221401,561270607,32969520
151,Myanmar,562529628,17668664,1191839742,2022577617,54179312
152,Namibia,155039402,3686768,259869028,64936035,2567024
153,Nauru,2775363,547,0,247098,12691
154,Nepal,948336200,11665246,2098924209,7615217941,30547586
155,Netherlands,6596240093,24697671,10477249376,4078636734,17564020
156,New Caledonia,52553289,250669,0,33746683,289959
157,New Zealand,1267142583,1584629,1377361446,6473706144,5185289
158,Nicaragua,14716658,272720,2067034,937729337,6948395
159,Niger,9109102,322511,6892217,103078565,26207982
160,Nigeria,266573557,3326391,326330278,2949392432,218541216
161,Niue,312955,0,0,20785,1952
162,North America,100070476453,1520182316,0,946985188676,600323657
163,North Korea,0,0,3763322,0,26069416
164,North Macedonia,305124296,9447071,242785365,163897657,2093606
165,Northern Cyprus,0,0,0,6950277,382836
166,Northern Ireland,0,0,0,2872544200,1896000
167,Northern Mariana Islands,9289698,28965,19490843,0,49574
168,Norway,1084548572,3556993,4315434983,5163271667,5434324
169,Oceania,8371081609,16915439,0,64532927603,45038860
170,Oman,390515777,4675574,6004203,202937980,4576300
171,Pakistan,1541396825,31244657,7275574847,74508479407,235824864
172,Palau,3874423,5343,890185,0,18084
173,Palestine,628360685,5507176,0,244175218,5250076
174,Panama,862228700,8949288,1922187942,597387626,4408582
175,Papua New Guinea,38850573,549806,249149,32331971,10142625
176,Paraguay,643366069,18129951,760128937,785138543,6780745
177,Peru,3819526044,235369615,8235414676,63971382767,34049588
178,Philippines,3493592503,56936090,9245408596,16433988108,115559008
179,Pitcairn,2104,0,0,465,47
180,Poland,5563602624,110977831,1865928483,43393309032,39857144
181,Portugal,4050295729,24999379,11524303421,2893603310,10270857
182,Puerto Rico,794487155,4922556,912141581,0,3252412
183,Qatar,432327206,715236,1469148232,2074961781,2695131
184,Reunion,334191581,701523,0,0,974062
185,Romania,2767481268,61952732,782262249,5505218353,19659270
186,Russia,17493520293,342752928,57999569801,51458202371,144713312
187,Rwanda,116732831,1325980,1429736328,776764090,13776702
188,Saint Barthelemy,4096251,4058,0,0,10994
189,Saint Helena,992134,0,0,24233,5401
190,Saint Kitts and Nevis,4918283,34962,8276023,3189974,47681
191,Saint Lucia,22787598,329024,6072050,16747857,179872
192,Saint Martin (French part),9425112,43684,0,0,31816
193,Saint Pierre and Miquelon,2154176,1087,0,0,5885
194,Saint Vincent and the Grenadines,7711991,93196,7146650,7195166,103959
195,Samoa,9983100,18245,0,13363183,222390
196,San Marino,17425745,130508,0,4277634,33690
197,Sao Tome and Principe,5684366,73125,23239,6650527,227393
198,Saudi Arabia,822523960,10519159,16396559891,11408142476,36408824
199,Scotland,0,0,0,5106148577,5466000
200,Senegal,85765949,1964029,389801991,113580746,17316452
201,Serbia,1976661177,15197270,3452055258,1195573557,6871547
202,Seychelles,39334709,145240,0,12369074,107135
203,Sierra Leone,7937015,142953,3280389,192725876,8605723
204,Singapore,1466930800,1236103,0,6273741807,5637022
205,Sint Maarten (Dutch part),8934203,85058,0,2613824,44192
206,Slovakia,1448437625,18986517,20992705500,295067101,5643455
207,Slovenia,967505409,8093865,1298032721,986734384,2119843
208,Solomon Islands,14162860,106473,0,14088284,724272
209,Somalia,25875751,1296529,1395353,185247910,17597508
210,South Africa,3807545323,101448434,9457796590,13558757696,59893884
211,South America,58561743915,1353241177,0,755332158582,436816679
212,South Korea,18155544512,21580660,20722710943,54496622819,51815808
213,South Sudan,17424452,153027,24885478,102616724,10913172
214,Spain,11258508579,123089865,34441958275,18758640286,47558632
215,Sri Lanka,592079607,14219043,2787300012,7676583103,21832150
216,Sudan,61849248,4672821,562941,204334353,46874200
217,Suriname,68391407,1218046,7611827,71501862,618046
218,Sweden,2273270495,22498619,6938162693,2961513637,10549349
219,Switzerland,3207661772,14332770,6507513712,10758287352,8740471
220,Syria,52035755,2989559,1320996,140039978,22125242
221,Taiwan,0,0,2042351429,23055926590,23893396
222,Tajikistan,20498253,145844,0,324439943,9952789
223,Tanzania,33111678,723183,883449,573246506,65497752
224,Thailand,3492382301,25746490,6881075209,45547040066,71697024
225,Timor,20315942,115274,7410803,122756634,1341298
226,Togo,34333451,271484,233029500,114080933,8848700
227,Tokelau,15046,0,0,18977,1893
228,Tonga,9932778,7614,0,4640848,106867
229,Trinidad and Tobago,139607066,3362227,190374458,500570767,1531043
230,Tunisia,982808343,27227692,482053473,2555890086,12356116
231,Turkey,13905129165,92528663,47891178076,63145737970,85341248
232,Turkmenistan,0,0,0,45295039,6430777
233,Turks and Caicos Islands,5597809,34361,0,1374005,45726
234,Tuvalu,1172335,197,0,156452,11335
235,Uganda,154112584,3267179,694072765,784433287,47249588
236,Ukraine,4631739109,96408932,4268844857,4271960957,39701744
237,United Arab Emirates,965772450,2415158,49581932031,5667655630,9441138
238,United Kingdom,19360388295,227234902,144400410838,60602545936,67508936
239,United States,83468691564,1045345773,344724615229,414280853474,338289856
240,United States Virgin Islands,18141249,109570,46075644,0,99479
241,Upper middle income,158531136132,2510250982,0,4463517367053,2525921300
242,Uruguay,802963871,6867023,1572780600,4438567622,3422796
243,Uzbekistan,136393562,840820,0,4350388514,34627648
244,Vanuatu,7319767,8701,23446,5057249,326744
245,Vatican,32702,0,0,0,808
246,Venezuela,502645909,5441223,0,347134856,28301700
247,Vietnam,7726411451,33908415,12473104912,42185002637,98186856
248,Wales,0,0,0,4800965467,3170000
249,Wallis and Futuna,1825650,6833,0,483705,11596
250,Western Sahara,0,0,3943,0,576005
251,World,547513329764,6481758440,0,10562917559575,7975105024
252,Yemen,11381219,2148079,666529,36235233,33696612
253,Zambia,297785576,3823248,1228012217,632532634,20017670
254,Zimbabwe,218305158,5134862,473769880,3211422214,16320539

## Separate Data Sets

Separate the data into **Deaths** data and **Vaccinations** data.

In [52]:
covid_data_deaths = df[['iso_code', 'continent', 'location', 'date', 'population',
                        'total_cases', 'new_cases', 'new_cases_smoothed',
                        'total_deaths', 'new_deaths', 'new_deaths_smoothed', 
                        'total_cases_per_million','new_cases_per_million', 'new_cases_smoothed_per_million', 
                        'total_deaths_per_million','new_deaths_per_million', 'new_deaths_smoothed_per_million',
                        'reproduction_rate', 
                        'icu_patients', 'icu_patients_per_million', 
                        'hosp_patients', 'hosp_patients_per_million',
                        'weekly_icu_admissions', 'weekly_icu_admissions_per_million', 
                        'weekly_hosp_admissions','weekly_hosp_admissions_per_million']]


covid_data_vaccinations = df[['iso_code', 'continent', 'location', 'date', 'population',
                             'total_tests', 'new_tests', 'total_tests_per_thousand','new_tests_per_thousand', 'new_tests_smoothed', 'new_tests_smoothed_per_thousand',
                             'positive_rate', 'tests_per_case', 'tests_units', 
                             'total_vaccinations', 'people_vaccinated','people_fully_vaccinated',
                             'total_boosters', 'new_vaccinations', 'new_vaccinations_smoothed',
                             'total_vaccinations_per_hundred', 'people_vaccinated_per_hundred',
                             'people_fully_vaccinated_per_hundred', 'total_boosters_per_hundred',
                             'new_vaccinations_smoothed_per_million', 'new_people_vaccinated_smoothed',
                             'new_people_vaccinated_smoothed_per_hundred', 'stringency_index', 'population_density',
                             'median_age', 'aged_65_older', 'aged_70_older', 
                             'gdp_per_capita', 'extreme_poverty',
                             'cardiovasc_death_rate', 'diabetes_prevalence', 'female_smokers', 'male_smokers',
                             'handwashing_facilities', 'hospital_beds_per_thousand', 'life_expectancy',
                             'human_development_index', 'excess_mortality_cumulative_absolute',
                             'excess_mortality_cumulative', 'excess_mortality', 'excess_mortality_cumulative_per_million']]

In [53]:
# double check deaths data
covid_data_deaths.info()

<class 'pandas.core.frame.DataFrame'>
Index: 367931 entries, 0 to 378555
Data columns (total 26 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   iso_code                            367931 non-null  object
 1   continent                           367931 non-null  object
 2   location                            367931 non-null  object
 3   date                                367931 non-null  object
 4   population                          367931 non-null  int64
 5   total_cases                         367931 non-null  int64
 6   new_cases                           367931 non-null  int64
 7   new_cases_smoothed                  367931 non-null  float64
 8   total_deaths                        367931 non-null  int64
 9   new_deaths                          367931 non-null  int64
 10  new_deaths_smoothed                 367931 non-null  float64
 11  total_cases_per_million             367931 non-null  float64
 12  new_cases_per_million               367931 non-null  float64
 13  new_cases_smoothed_per_million      367931 non-null  float64
 14  total_deaths_per_million            367931 non-null  float64
 15  new_deaths_per_million              367931 non-null  float64
 16  new_deaths_smoothed_per_million     367931 non-null  float64
 17  reproduction_rate                   367931 non-null  float64
 18  icu_patients                        367931 non-null  int64
 19  icu_patients_per_million            367931 non-null  float64
 20  hosp_patients                       367931 non-null  int64
 21  hosp_patients_per_million           367931 non-null  float64
 22  weekly_icu_admissions               367931 non-null  int64
 23  weekly_icu_admissions_per_million   367931 non-null  float64
 24  weekly_hosp_admissions              367931 non-null  int64
 25  weekly_hosp_admissions_per_million  367931 non-null  float64
dtypes: float64(13), int64(9), object(4)
memory usage: 75.8+ MB

In [54]:
# double check vaccinations data
covid_data_vaccinations.info()

<class 'pandas.core.frame.DataFrame'>
Index: 367931 entries, 0 to 378555
Data columns (total 46 columns):
 #   Column                                      Non-Null Count   Dtype
---  ------                                      --------------   -----
 0   iso_code                                    367931 non-null  object
 1   continent                                   367931 non-null  object
 2   location                                    367931 non-null  object
 3   date                                        367931 non-null  object
 4   population                                  367931 non-null  int64
 5   total_tests                                 367931 non-null  int64
 6   new_tests                                   367931 non-null  int64
 7   total_tests_per_thousand                    367931 non-null  float64
 8   new_tests_per_thousand                      367931 non-null  float64
 9   new_tests_smoothed                          367931 non-null  float64
 10  new_tests_smoothed_per_thousand             367931 non-null  float64
 11  positive_rate                               367931 non-null  float64
 12  tests_per_case                              367931 non-null  float64
 13  tests_units                                 367931 non-null  object
 14  total_vaccinations                          367931 non-null  int64
 15  people_vaccinated                           367931 non-null  int64
 16  people_fully_vaccinated                     367931 non-null  int64
 17  total_boosters                              367931 non-null  int64
 18  new_vaccinations                            367931 non-null  int64
 19  new_vaccinations_smoothed                   367931 non-null  float64
 20  total_vaccinations_per_hundred              367931 non-null  float64
 21  people_vaccinated_per_hundred               367931 non-null  float64
 22  people_fully_vaccinated_per_hundred         367931 non-null  float64
 23  total_boosters_per_hundred                  367931 non-null  float64
 24  new_vaccinations_smoothed_per_million       367931 non-null  float64
 25  new_people_vaccinated_smoothed              367931 non-null  float64
 26  new_people_vaccinated_smoothed_per_hundred  367931 non-null  float64
 27  stringency_index                            367931 non-null  float64
 28  population_density                          367931 non-null  float64
 29  median_age                                  367931 non-null  float64
 30  aged_65_older                               367931 non-null  float64
 31  aged_70_older                               367931 non-null  float64
 32  gdp_per_capita                              367931 non-null  float64
 33  extreme_poverty                             367931 non-null  float64
 34  cardiovasc_death_rate                       367931 non-null  float64
 35  diabetes_prevalence                         367931 non-null  float64
 36  female_smokers                              367931 non-null  float64
 37  male_smokers                                367931 non-null  float64
 38  handwashing_facilities                      367931 non-null  float64
 39  hospital_beds_per_thousand                  367931 non-null  float64
 40  life_expectancy                             367931 non-null  float64
 41  human_development_index                     367931 non-null  float64
 42  excess_mortality_cumulative_absolute        367931 non-null  float64
 43  excess_mortality_cumulative                 367931 non-null  float64
 44  excess_mortality                            367931 non-null  float64
 45  excess_mortality_cumulative_per_million     367931 non-null  float64
dtypes: float64(33), int64(8), object(5)
memory usage: 131.9+ MB

### Convert data to csv file for further analysis

In [60]:
# Save owid_covid_data_deaths to CSV and Excel
covid_data_deaths.to_csv('owid_covid_data_deaths.csv', index=False)
covid_data_deaths.to_excel('owid_covid_data_deaths.xlsx', index=False)

# Save owid_covid_data_vaccinations to CSV and Excel
covid_data_vaccinations.to_csv('owid_covid_data_vaccinations.csv', index=False)
covid_data_vaccinations.to_excel('owid_covid_data_vaccinations.xlsx', index=False)